# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build LXLDevHelper-generate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew    
    - name: Build with Gradle
      run: ./gradlew build
    - name: Copy file
      run: cp -a ./build/libs/*.jar Generate.jar
    - name: ls
      run: ls
    - name: commit
      run: |
        git config --global user.email 3601594248@qq.com
        git config --global user.name moxicat
        git add Generate.jar
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: LiteLDev-LXL/LXLDevHelper-DocSrc
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
